export const produtos = [
  {
    id: 1,
    nome: "Adaga",
    preco: "25.00",
    secao: "Armas",
    categorias: ["equipamentos", "1 mão", "físico", "arremesso"],
    img: "./src/img/equipamentos/armas/adaga2.jpeg",
    modificador: "Dano 1",
    alcance: "Alcance: Perto",
    especial: "+1 Ferimento ao atacar inimigo que não te viu",
    disponivel: true,
  },
  {
    id: 2,
    nome: "Alabarda",
    preco: "300.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "físico"],
    img: "./src/img/equipamentos/armas/alabarda.jpg",
    modificador: "Dano 3",
    alcance: "Alcance: Perto",
    especial: "+1 Ferimento ao atacar inimigo que não te viu",
    disponivel: true,
  },
  {
    id: 3,
    nome: "Machado",
    preco: "150.00",
    secao: "Armas",
    categorias: ["equipamentos", "1 mão", "físico", "arremesso"],
    img: "./src/img/equipamentos/armas/axe.webp",
    modificador: "Dano 2",
    alcance: "Alcance: Perto",
    especial: "Bônus em ações de destruir objetos",
    disponivel: true,
  },
  {
    id: 4,
    nome: "Machado de batalha ",
    preco: "300.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "físico"],
    img: "./src/img/equipamentos/armas/battleaxe.webp",
    modificador: "Dano 1",
    alcance: "Alcance: Perto",
    especial: "Bônus em ações de destruir objetos",
    disponivel: true,
  },
  {
    id: 5,
    nome: "Espada larga",
    preco: "300.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "físico"],
    img: "./src/img/equipamentos/armas/longsword.jpg",
    modificador: "Dano 3",
    alcance: "Alcance: Perto",
    especial: "Nada",
    disponivel: true,
  },
  {
    id: 6,
    nome: "Espada curta",
    preco: "150.00",
    secao: "Armas",
    categorias: ["equipamentos", "1 mão", "físico"],
    img: "./src/img/equipamentos/armas/Short_Sword.webp",
    modificador: "Dano 2",
    alcance: "Alcance: Perto",
    especial: "Nada",
    disponivel: true,
  },
  {
    id: 7,
    nome: "Lança",
    preco: "150.00",
    secao: "Armas",
    categorias: ["equipamentos", "1 mão", "físico", "arremesso"],
    img: "./src/img/equipamentos/armas/lanca.webp",
    modificador: "Dano 2",
    alcance: "Alcance: Perto",
    especial: "Pode ser arremessada",
    disponivel: true,
  },
  {
    id: 8,
    nome: "Soqueira",
    preco: "25.00",
    secao: "Armas",
    categorias: ["equipamentos", "1 mão", "físico"],
    img: "./src/img/equipamentos/armas/soqueira.jpg",
    modificador: "Dano 1",
    alcance: "Alcance: Perto",
    especial: "Nada",
    disponivel: true,
  },
  {
    id: 9,
    nome: "Arco curto",
    preco: "50.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/equipamentos/armas/bow.jpg",
    modificador: "Dano 1 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Pode utilizar diversos tipos de flechas",
    disponivel: true,
  },
  {
    id: 10,
    nome: "Arco Longo",
    preco: "300.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/equipamentos/armas/bow.jpg",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Pode utilizar diversos tipos de flechas",
    disponivel: true,
  },
  {
    id: 11,
    nome: "Besta",
    preco: "200.00",
    secao: "Armas",
    categorias: ["equipamentos", "1 mão", "longa distância"],
    img: "./src/img/equipamentos/armas/crossbow.png",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Pode utilizar diversos tipos de virotes",
    disponivel: true,
  },
  {
    id: 12,
    nome: "Grande besta",
    preco: "400.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/equipamentos/armas/giantcrossbow.png",
    modificador: "Dano 3 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Pode utilizar diversos tipos de virotes",
    disponivel: true,
  },
  {
    id: 13,
    nome: "Pistola",
    preco: "100.00",
    secao: "Armas",
    categorias: ["equipamentos", "1 mão", "longa distância"],
    img: "./src/img/equipamentos/armas/pistol.jpeg",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial:
      "Pode utilizar diversos tipos de balas, mas precisa de uma ação para recarregar ao tirar um 1 no dado",
    disponivel: true,
  },
  {
    id: 14,
    nome: "Rifle",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/equipamentos/armas/musket.png",
    modificador: "Dano 3 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial:
      "Pode utilizar diversos tipos de balas, mas precisa de uma ação para recarregar ao tirar um 1 no dado",
    disponivel: true,
  },
  {
    id: 15,
    nome: "Chakram",
    preco: "30.00",
    secao: "Armas",
    categorias: ["equipamentos", "1 mão", "longa distância"],
    img: "./src/img/equipamentos/armas/chakram.webp",
    modificador: "Dano 1",
    alcance: "Alcance: Longe",
    especial: "Bônus em ações de cortar objetos a distância",
    disponivel: true,
  },
  {
    id: 16,
    nome: "Zarabatana",
    preco: "50.00",
    secao: "Armas",
    categorias: ["equipamentos", "1 mão", "longa distância"],
    img: "./src/img/equipamentos/armas/zarabatana.jpg",
    modificador: "Dano 1",
    alcance: "Alcance: Longe",
    especial: "Pode utilizar diversos tipos de dardos",
    disponivel: true,
  },
  /* Armaduras */
  {
    id: 17,
    nome: "Armadura leve",
    preco: "100.00",
    secao: "Armaduras",
    categorias: ["equipamentos", "armadura"],
    img: "./src/img/equipamentos/armaduras/leve.webp",
    modificador: "Armadura 1",
    alcance: " ",
    especial: "Bônus em ações de furtividade",
    disponivel: true,
  },
  {
    id: 18,
    nome: "Armadura básica",
    preco: "250.00",
    secao: "Armaduras",
    categorias: ["equipamentos", "armadura"],
    img: "./src/img/equipamentos/armaduras/medium.png",
    modificador: "Armadura 2",
    alcance: " ",
    especial: " ",
    disponivel: true,
  },
  {
    id: 19,
    nome: "Armadura pesada",
    preco: "500.00",
    secao: "Armaduras",
    categorias: ["equipamentos", "armadura"],
    img: "./src/img/equipamentos/armaduras/heavy.webp",
    modificador: "Armadura 3",
    alcance: " ",
    especial: "Penalidade em ações de furtividade",
    disponivel: true,
  },
  /* Escudos */
  {
    id: 20,
    nome: "Escudo pequeno",
    preco: "100.00",
    secao: "Escudos",
    categorias: ["equipamentos", "escudo"],
    img: "./src/img/equipamentos/escudos/wood.webp",
    modificador: "Defesa +1",
    alcance: " ",
    especial: " ",
    disponivel: true,
  },
  {
    id: 21,
    nome: "Escudo médio",
    preco: "250.00",
    secao: "Escudos",
    categorias: ["equipamentos", "escudo"],
    img: "./src/img/equipamentos/escudos/medium.jpg",
    modificador: "Defesa +2",
    alcance: " ",
    especial: "Físico 4 ou melhor para utilizá-lo",
    disponivel: true,
  },
  {
    id: 22,
    nome: "Escudo Torre",
    preco: "100.00",
    secao: "Escudos",
    categorias: ["equipamentos", "escudo"],
    img: "./src/img/equipamentos/escudos/heavy.jpg",
    modificador: "Defesa +3",
    alcance: " ",
    especial: "Físico 3 ou melhor para utilizá-lo",
    disponivel: true,
  },
  /* Consumiveis */
  {
    id: 23,
    nome: "Antidoto",
    preco: "30.00",
    secao: "Consumíveis",
    categorias: ["consumiveis", "suporte"],
    img: "./src/img/consumiveis/antidoto.png",
    modificador: " ",
    alcance: " ",
    especial: "Remove o efeito 'Envenenado'",
    disponivel: true,
  },
  {
    id: 24,
    nome: "Veneno",
    preco: "50.00",
    secao: "Consumíveis",
    categorias: ["consumiveis", "prejudicial"],
    img: "./src/img/consumiveis/veneno.jpg",
    modificador: " ",
    alcance: " ",
    especial:
      "Adiciona o efeito de envenenado. Ao ser aplicado em uma arma seu próximo ataque envenena o oponente.",
    disponivel: false,
  },
  {
    id: 25,
    nome: "Poção da sorte",
    preco: "150.00",
    secao: "Consumíveis",
    categorias: ["consumiveis", "suporte"],
    img: "./src/img/consumiveis/bonus.jpg",
    modificador: " ",
    alcance: " ",
    especial: "Concede Bônus ao usuário por 2 rodadas.",
    disponivel: false,
  },
  {
    id: 26,
    nome: "Poção do sono",
    preco: "200.00",
    secao: "Consumíveis",
    categorias: ["consumiveis", "prejudicial"],
    img: "./src/img/consumiveis/sono.jpg",
    modificador: " ",
    alcance: " ",
    especial:
      "Faz com que o alvo durma por 3 rodadas (1 hora fora de combate), ou até que ele sofra dano.",
    disponivel: true,
  },
  {
    id: 27,
    nome: "Poção do azar",
    preco: "150.00",
    secao: "Consumíveis",
    categorias: ["consumiveis", "prejudicial"],
    img: "./src/img/consumiveis/azar.jpg",
    modificador: " ",
    alcance: " ",
    especial: "Aplica Penalidade ao alvo por 2 rodadas",
    disponivel: false,
  },
  {
    id: 28,
    nome: "Pólvora",
    preco: "25.00",
    secao: "Consumíveis",
    categorias: ["consumiveis", "utilidades"],
    img: "./src/img/consumiveis/polvora.jpg",
    modificador: " ",
    alcance: " ",
    especial: "Utilizada para criar itens explosivos",
    disponivel: true,
  },
  {
    id: 29,
    nome: "Munição de prata",
    preco: "40.00",
    secao: "Consumíveis",
    categorias: ["consumiveis", "munição"],
    img: "./src/img/consumiveis/balas.jpg",
    modificador: "+1 ferimento contra criaturas mágicas",
    alcance: " ",
    especial: "Duram até o final do combate",
    disponivel: true,
  },
  {
    id: 30,
    nome: "Munição explosivas",
    preco: "50.00",
    secao: "Consumíveis",
    categorias: ["consumiveis", "munição"],
    img: "./src/img/consumiveis/balas.jpg",
    modificador: "+1 Ferimento",
    alcance: " ",
    especial: "Duram até o final do combate",
    disponivel: false,
  },
  {
    id: 31,
    nome: "Munição envenenada",
    preco: "50.00",
    secao: "Consumíveis",
    categorias: ["consumiveis", "munição"],
    img: "./src/img/consumiveis/balas.jpg",
    modificador: " ",
    alcance: " ",
    especial: "Aplica 'Envenenado' ao atingir o alvo",
    disponivel: false,
  },
  /* Variedades */
  {
    id: 32,
    nome: "Dados viciados",
    preco: "40.00",
    secao: "Variedades",
    categorias: ["variedades", "utilidades"],
    img: "./src/img/variedades/loaded-dice.jpg",
    modificador: " ",
    alcance: " ",
    especial: "Anuncie ao mestre que está trapaceando para ativar.",
    disponivel: false,
  },
  {
    id: 33,
    nome: "Kit de cartografia",
    preco: "150.00",
    secao: "Variedades",
    categorias: ["variedades", "utilidades"],
    img: "./src/img/variedades/cartografia.webp",
    modificador: " ",
    alcance: " ",
    especial: "Bônus em ações de cartografia",
    disponivel: true,
  },
  {
    id: 34,
    nome: "Kit de costura",
    preco: "60.00",
    secao: "Variedades",
    categorias: ["variedades", "utilidades"],
    img: "./src/img/variedades/custura.webp",
    modificador: " ",
    alcance: " ",
    especial: "Bônus em ações de custura, inclusive reparos de armaduras leves",
    disponivel: true,
  },
  {
    id: 35,
    nome: "Bigorna Portátil",
    preco: "250.00",
    secao: "Variedades",
    categorias: ["variedades", "utilidades"],
    img: "./src/img/variedades/forja.webp",
    modificador: " ",
    alcance: " ",
    especial:
      "Bônus em ações relacionadas a forja, incluindo o reparo de armaduras pesadas",
    disponivel: false,
  },
  {
    id: 36,
    nome: "Kit de alquimia portátil",
    preco: "200.00",
    secao: "Variedades",
    categorias: ["variedades", "utilidades"],
    img: "./src/img/variedades/lab.webp",
    modificador: " ",
    alcance: " ",
    especial: "Permite a criação de poções quando em viagem",
    disponivel: true,
  },
  {
    id: 37,
    nome: "Kit de disfarces",
    preco: "160.00",
    secao: "Variedades",
    categorias: ["variedades", "utilidades"],
    img: "./src/img/variedades/disfarce.jpg",
    modificador: " ",
    alcance: " ",
    especial: "Bônus em ações de disfarce",
    disponivel: false,
  },
  {
    id: 38,
    nome: "Kit de falsificação",
    preco: "300.00",
    secao: "Variedades",
    categorias: ["variedades", "utilidades"],
    img: "./src/img/variedades/falsificar.jpg",
    modificador: " ",
    alcance: " ",
    especial: "Permite que o usuário tente falsificar documentos.",
    disponivel: false,
  },
  {
    id: 39,
    nome: "Burro de carga",
    preco: "300.00",
    secao: "Variedades",
    categorias: ["variedades", "transporte"],
    img: "./src/img/variedades/donkey.jpg",
    modificador: " ",
    alcance: " ",
    especial:
      "Ajuda a transportar materiais e pessoas, além de ser treinado para se esconder em casos de perigo",
    disponivel: true,
  },
  {
    id: 40,
    nome: "Carroça",
    preco: "400.00",
    secao: "Variedades",
    categorias: ["variedades", "transporte"],
    img: "./src/img/variedades/wagon.jpg",
    modificador: " ",
    alcance: " ",
    especial:
      "Uma das formas mais comuns de transporte, podendo funcionar como uma base de operações móvel. Cavalo não incluído.",
    disponivel: true,
  },
  {
    id: 41,
    nome: "Gancho ninja",
    preco: "50.00",
    secao: "Variedades",
    categorias: ["variedades", "utilidades"],
    img: "./src/img/variedades/gancho.jpg",
    modificador: " ",
    alcance: " ",
    especial: "Bônus em ações de escalada",
    disponivel: false,
  },
];
