export const produtos = [
  {
    id: 1,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/arco-magico.jpeg",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 2,
    nome: "Armadura da miragem",
    preco: "650.00",
    secao: "Armaduras",
    categorias: ["equipamentos", "armadura"],
    img: "./src/img/magicos/arm-leve-magica.jpg",
    modificador: "Armadura 2",
    alcance: " ",
    especial:
      "Permite que o usuário crie uma ilusão ao seu redor, mudando sua aparência.",
    disponivel: true,
  },
  {
    id: 3,
    nome: "Armadura silenciosa",
    preco: "1500.00",
    secao: "Armaduras",
    categorias: ["equipamentos", "armadura"],
    img: "./src/img/magicos/arm-pes-magica.jpg",
    modificador: "Armadura 3",
    alcance: " ",
    especial: "Bônus ao fazer ações de furtividade",
    disponivel: true,
  },
  {
    id: 4,
    nome: "Cajado venenoso",
    preco: "750.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/cajado-magico.jpg",
    modificador: "Dano 2",
    alcance: "Alcance: Perto | Longe",
    especial:
      "Permite que o usuário dispare um raio venenoso a longas distancias. Se o alvo falhar em um teste de Físico ele fica Envenenado por 3 rodadas, recebendo 1 Ferimento.",
    disponivel: true,
  },
  {
    id: 5,
    nome: "Chakram incendiario",
    preco: "400.00",
    secao: "Armas",
    categorias: ["equipamentos", "1 mão", "longa distância"],
    img: "./src/img/magicos/chakram-magico.jpg",
    modificador: "Dano 2 | Dano 3 (Encantar arma: Fogo)",
    alcance: "Alcance: Longe",
    especial:
      "Você pode usar uma ação para ativar a técnica 'Encantar Arma: Fogo', aumentando os ferimentos em +1 por 3 rodadas. | Bônus em ações de cortar a distância.",
    disponivel: true,
  },
  {
    id: 6,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/chicote-magico.web",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 7,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Escudos",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/escudo-magico.jpg",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 8,
    nome: "Espada chicote",
    preco: "550.00",
    secao: "Armas",
    categorias: ["equipamentos", "1 mão", "curta distância"],
    img: "./src/img/magicos/espada-chicote.jpg",
    modificador: "Dano 3 (Espada) | Dano 2 (Chicote)",
    alcance: "Alcance: Perto",
    especial: "Quando em modo chicote o alvo possui penalidade em sua reação.",
    disponivel: true,
  },
  {
    id: 9,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/espada-magica.jpg",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 10,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/espada-magica2.jpg",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 11,
    nome: "Adaga debilitante",
    preco: "700.00",
    secao: "Armas",
    categorias: ["equipamentos", "1 mão", "curta distância"],
    img: "./src/img/magicos/faca-magica.webp",
    modificador: "Dano 2",
    alcance: "Alcance: Perto | Longe",
    especial:
      "Ao tirar um 6 no dado o alvo fica debilitado, perdendo 1 ponto de defesa pelas próximas 2 rodadas.",
    disponivel: true,
  },
  {
    id: 12,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/faca-multiforma.webp",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 13,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/facas-arremesso.png",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 14,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/foice-magica.jpg",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 15,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/gunblade.webp",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 16,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/katana-magica.jpg",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 17,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/lanca-magica.webp",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 18,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/livro-magia.webp",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 19,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/luvas-magicas.jpg",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 20,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/machado-magico.webp",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 21,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/ovos.jpeg",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 22,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/pocoes.jpg",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 23,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/revolver-magico.jpg",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 24,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/rifle-magico.jpg",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 25,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/scrolls.jpeg",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 26,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/shuriken-magica.png",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 27,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/vasoura-voadora.avif",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
  {
    id: 28,
    nome: "Arco Agulha",
    preco: "500.00",
    secao: "Armas",
    categorias: ["equipamentos", "2 mãos", "longa distância"],
    img: "./src/img/magicos/vasoura-voadora.avif",
    modificador: "Dano 2 (varia de acordo com a munição)",
    alcance: "Alcance: Longe",
    especial: "Suas flechas ignoram a armadura do alvo",
    disponivel: true,
  },
];
